### ISSUE TITLE
B in formula nr 3

### ISSUE THREAD

**Issue by ricardojdferreira** [Unbabel/data-science-challenge#2]
What is the B in formula nr 3?
![image](https://user-images.githubusercontent.com/11673268/54497921-595f0700-48f8-11e9-9f69-8b999b9905b6.png)

The formula takes different shapes if Skill of Editor is in or does not belong to **B**.

**Comment by JoaoVasques** [comment]
Hi @ricardojdferreira ,

I've updated the master branch with an updated description of what that term means. Hope this answer your question.

Thanks,
JV

**Comment by JoaoVasques** [comment]
Updated on master now
