### ISSUE TITLE
Sentence not complete?

### ISSUE THREAD

**Issue by ricardojdferreira** [Unbabel/data-science-challenge#3]
In the following sentence, it looks like there is something else to be explained:
![image](https://user-images.githubusercontent.com/11673268/54497999-3ed95d80-48f9-11e9-90c7-b61ae59cdf04.png)

**Comment by JoaoVasques** [comment]
Oops 😄 Is a typo. Going to fix it. Thanks

**Comment by JoaoVasques** [comment]
Updated on master now
