### ISSUE TITLE
Table Tickets with duplicated headers

### ISSUE THREAD

**Issue by ricardojdferreira** [Unbabel/data-science-challenge#4]
The following image is a snippet of the header + some data, where one can see duplicated instances of Client ID. 
However, the first appearance seems to be a rather different thing. 
Could you please clarify? Thanks!
![image](https://user-images.githubusercontent.com/11673268/54498032-9ed00400-48f9-11e9-8ef7-b4420afe98c9.png)

**Comment by JoaoVasques** [comment]
Hi @ricardojdferreira ,

Entrances of the same`client_id` means that they're tickets from the same client. It's something that is expected.

Does this answer your question?
Thanks!
